export {
  TaxEngine,
  TaxService,
  calculateGST,
  calculateVAT,
  calculateSalesTax,
  calculateLineItemTaxes,
  summarizeTax,
  detectTaxType,
  defaultRateFor,
  isEuCountry,
  normalizeRegionCode,
  EU_VAT_RATES,
  US_SALES_TAX_RATES,
} from "./TaxEngine";
